blueprint:
  name: WarmTemperatureNotifer
  description: WarmTemperatureNotiferDesc
  domain: automation
  input:
    temperature_sensor:
      name: Sensor to monitor
      description: This sensor will mave the temperature checked.
      selector:
        entity:
          domain: sensor
trigger:
  - platform: numeric_state
    entity_id: "{{ input('temperature_sensor') }}"
    above: 25
condition: []
action:
  - service: notify.roselawn_gmail
    data:
      title: Blue Freezer too warm - WATCH
      message: >-
        Rev 1 Temperature below 25. Currently "{{ input('temperature_sensor') }}"°C.
  - condition: numeric_state
    entity_id: !input temperature_sensor
    above: 25
  - delay:
      minutes: 1
  - repeat:
      until:
        - condition: numeric_state
          entity_id: !input temperature_sensor
          below: 25
      sequence:
        - delay:
            minutes: 1
        - service: notify.roselawn_gmail
          data:
            title: Blue Freezer still too warm rpt
            message: >-
              Rev 1 The temperature in your freezer is "{{ input('temperature_sensor') }}"°C and has been too warm for 2
              minutes. Checking again in 1 minutes.
  - service: notify.roselawn_gmail
    data:
      title: Blue Freezer temperature back to normal
      message: >-
        Rev 1 The temperature in your freezer is "{{ input('temperature_sensor') }}"°C and is back to a safe level.
mode: single
