blueprint:
  name: Motion Light Tutorial
  description: Turn a light on based on detected motion
  domain: automation
  input:
    temperature_sensor:
alias: WarmTemperatureNotifer
description: ""
trigger:
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: 25
condition: []
action:
  - service: notify.roselawn_gmail
    data:
      title: Freezer too warm - WATCH
      message: >-
        Temperature below 25. Currently greater°C.
