blueprint:
  name: WarmTemperatureNotifer
  description: WarmTemperatureNotiferDesc
  domain: automation
  input:
    temperature_sensor:
      name: Sensor to monirow
      description: This sensor will be synchronized with the light.
      selector:
        entity:
          domain: sensor
trigger:
  - platform: numeric_state
    entity_id: !input temperature_sensor
    above: 25
condition: []
action:
  - service: notify.roselawn_gmail
    data:
      title: Freezer too warm - WATCH
      message: >-
        Temperature below 25. Currently greater°C.
