blueprint:
  name: WarmTemperatureNotifer v0.1
  description: Send an e-mail when the temperature reaches above a threshold
  domain: automation
  input:
    temperature_sensor:
      name: Sensor to monitor
      description: This sensor will mave the temperature checked.
      selector:
        entity:
          domain: sensor
    threshold:
      name: Temperature Threshold
      description: The temperature threshold in degrees.
      default: 23.9
      selector:
        number:

variables:
  temperature_sensor: !input "temperature_sensor"
  threshold: !input "threshold"

trigger:
  - platform: numeric_state
    entity_id: !input "temperature_sensor"
    above: !input "threshold"

condition: []
action:
  - service: notify.roselawn_gmail
    data:
      title: Watch - Blue Freezer
      message: >-
        Temperature above {{ threshold | float(-999) }}. Currently {{ states(temperature_sensor) | float }}°C
  - condition: numeric_state
    entity_id: !input "temperature_sensor"
    above: !input "threshold"
  - delay:
      minutes: 2
  - repeat:
      until:
        - condition: numeric_state
          entity_id: !input "temperature_sensor"
          below: !input "threshold"
      sequence:
        - service: notify.roselawn_gmail
          data:
            title: Error - Blue Freezer.
            message: >-
              The temperature in your freezer is {{ states(temperature_sensor) | float }}°C and is still over {{ threshold | float(-999) }}.
        - delay:
            minutes: 2
  - service: notify.roselawn_gmail
    data:
      title: Wait - Blue Freezer
      message: >-
        The temperature in your freezer is {{ states(temperature_sensor) | float }}°C and is back to under {{ threshold | float(-999) }}.
mode: single
